# Generated by Django 2.0.7 on 2018-07-08 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0002_auto_20180708_0933'),
    ]

    operations = [
        migrations.CreateModel(
            name='Benefits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='relation',
            name='count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='relation',
            name='benefits',
            field=models.ManyToManyField(to='graph.Benefits'),
        ),
    ]
