# Generated by Django 2.0.7 on 2018-07-08 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0003_auto_20180708_1042'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Benefits',
            new_name='Benefit',
        ),
    ]
