# Generated by Django 2.0.7 on 2018-07-08 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0005_person_is_good_payer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='person_one',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_one', to='graph.Person'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='person_two',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_two', to='graph.Person'),
        ),
    ]
